// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Clock_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_DashBoardScreen
void ui_DashBoardScreen_screen_init(void);
void ui_event_DashBoardScreen(lv_event_t * e);
lv_obj_t * ui_DashBoardScreen;
lv_obj_t * ui_TopBar;
lv_obj_t * ui_Welcome;
lv_obj_t * ui_WiFiIcon;
lv_obj_t * ui_LeftBar;
lv_obj_t * ui_RightBar;
lv_obj_t * ui_HHH;
lv_obj_t * ui_MMM;
lv_obj_t * ui_Dot;
lv_obj_t * ui_Month;
lv_obj_t * ui_Date;
lv_obj_t * ui_Vaar;
lv_obj_t * ui_Coma;
lv_obj_t * ui_TemperatureIcon;
lv_obj_t * ui_HumidityIcon;
lv_obj_t * ui_WindIcon;
lv_obj_t * ui_RainIcon;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_WindSpeed;
lv_obj_t * ui_Rain;
lv_obj_t * ui_TemperatureUnit;
lv_obj_t * ui_HumidityUnit;
lv_obj_t * ui_WindSpeedUnit;
lv_obj_t * ui_RainUnit;
lv_obj_t * ui_BottomBar;
lv_obj_t * ui_Location;
lv_obj_t * ui_SmartHomeIcon;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Clock_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_DashBoardScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Clock_Animation(ui_Dot, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_DashBoardScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_DashBoardScreen);
}
