// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void Clock_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_DashBoardScreen
void ui_DashBoardScreen_screen_init(void);
void ui_event_DashBoardScreen(lv_event_t * e);
extern lv_obj_t * ui_DashBoardScreen;
extern lv_obj_t * ui_TopBar;
extern lv_obj_t * ui_Welcome;
extern lv_obj_t * ui_WiFiIcon;
extern lv_obj_t * ui_LeftBar;
extern lv_obj_t * ui_RightBar;
extern lv_obj_t * ui_HHH;
extern lv_obj_t * ui_MMM;
extern lv_obj_t * ui_Dot;
extern lv_obj_t * ui_Month;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Vaar;
extern lv_obj_t * ui_Coma;
extern lv_obj_t * ui_TemperatureIcon;
extern lv_obj_t * ui_HumidityIcon;
extern lv_obj_t * ui_WindIcon;
extern lv_obj_t * ui_RainIcon;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_WindSpeed;
extern lv_obj_t * ui_Rain;
extern lv_obj_t * ui_TemperatureUnit;
extern lv_obj_t * ui_HumidityUnit;
extern lv_obj_t * ui_WindSpeedUnit;
extern lv_obj_t * ui_RainUnit;
extern lv_obj_t * ui_BottomBar;
extern lv_obj_t * ui_Location;
extern lv_obj_t * ui_SmartHomeIcon;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/WiFi.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/Temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/Humidity.png
LV_IMG_DECLARE(ui_img_windspeed_png);    // assets/WindSpeed.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets/Rain.png
LV_IMG_DECLARE(ui_img_smarthome_png);    // assets/SmartHome.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
