// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

void ui_DashBoardScreen_screen_init(void)
{
    ui_DashBoardScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DashBoardScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DashBoardScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashBoardScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBar = lv_obj_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_TopBar, 300);
    lv_obj_set_height(ui_TopBar, 28);
    lv_obj_set_x(ui_TopBar, 9);
    lv_obj_set_y(ui_TopBar, 6);
    lv_obj_clear_flag(ui_TopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBar, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TopBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Welcome = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_Welcome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Welcome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Welcome, 7);
    lv_obj_set_y(ui_Welcome, 4);
    lv_label_set_text(ui_Welcome, "Welcome Smart Home");
    lv_obj_set_style_text_color(ui_Welcome, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Welcome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiIcon = lv_img_create(ui_TopBar);
    lv_img_set_src(ui_WiFiIcon, &ui_img_wifi_png);
    lv_obj_set_width(ui_WiFiIcon, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_WiFiIcon, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_WiFiIcon, 259);
    lv_obj_set_y(ui_WiFiIcon, -9);
    lv_obj_add_flag(ui_WiFiIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WiFiIcon, 125);

    ui_LeftBar = lv_obj_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_LeftBar, 118);
    lv_obj_set_height(ui_LeftBar, 195);
    lv_obj_set_x(ui_LeftBar, 9);
    lv_obj_set_y(ui_LeftBar, 39);
    lv_obj_clear_flag(ui_LeftBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LeftBar, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LeftBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LeftBar, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LeftBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LeftBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightBar = lv_obj_create(ui_DashBoardScreen);
    lv_obj_remove_style_all(ui_RightBar);
    lv_obj_set_width(ui_RightBar, 176);
    lv_obj_set_height(ui_RightBar, 149);
    lv_obj_set_x(ui_RightBar, 136);
    lv_obj_set_y(ui_RightBar, 59);
    lv_obj_clear_flag(ui_RightBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HHH = lv_label_create(ui_RightBar);
    lv_obj_set_width(ui_HHH, 71);
    lv_obj_set_height(ui_HHH, 48);
    lv_obj_set_x(ui_HHH, 8);
    lv_obj_set_y(ui_HHH, 16);
    lv_label_set_text(ui_HHH, "00");
    lv_obj_set_style_text_color(ui_HHH, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HHH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HHH, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HHH, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MMM = lv_label_create(ui_RightBar);
    lv_obj_set_width(ui_MMM, 71);
    lv_obj_set_height(ui_MMM, 48);
    lv_obj_set_x(ui_MMM, 97);
    lv_obj_set_y(ui_MMM, 16);
    lv_label_set_text(ui_MMM, "00");
    lv_obj_set_style_text_color(ui_MMM, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MMM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MMM, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MMM, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dot = lv_label_create(ui_RightBar);
    lv_obj_set_width(ui_Dot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dot, 82);
    lv_obj_set_y(ui_Dot, 13);
    lv_label_set_text(ui_Dot, ":");
    lv_obj_set_style_text_color(ui_Dot, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dot, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Month = lv_label_create(ui_RightBar);
    lv_obj_set_width(ui_Month, 48);
    lv_obj_set_height(ui_Month, 25);
    lv_obj_set_x(ui_Month, 86);
    lv_obj_set_y(ui_Month, 84);
    lv_label_set_text(ui_Month, "Jan");
    lv_obj_set_style_text_color(ui_Month, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Month, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Month, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_RightBar);
    lv_obj_set_width(ui_Date, 37);
    lv_obj_set_height(ui_Date, 23);
    lv_obj_set_x(ui_Date, 131);
    lv_obj_set_y(ui_Date, 84);
    lv_label_set_text(ui_Date, "22");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vaar = lv_label_create(ui_RightBar);
    lv_obj_set_width(ui_Vaar, 53);
    lv_obj_set_height(ui_Vaar, 30);
    lv_obj_set_x(ui_Vaar, 18);
    lv_obj_set_y(ui_Vaar, 84);
    lv_label_set_text(ui_Vaar, "Mon");
    lv_obj_set_style_text_color(ui_Vaar, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Vaar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Vaar, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Vaar, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Coma = lv_label_create(ui_RightBar);
    lv_obj_set_width(ui_Coma, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Coma, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Coma, 70);
    lv_obj_set_y(ui_Coma, 86);
    lv_label_set_text(ui_Coma, ",");
    lv_obj_set_style_text_color(ui_Coma, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Coma, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Coma, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureIcon = lv_img_create(ui_DashBoardScreen);
    lv_img_set_src(ui_TemperatureIcon, &ui_img_temperature_png);
    lv_obj_set_width(ui_TemperatureIcon, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_TemperatureIcon, LV_SIZE_CONTENT);    /// 81
    lv_obj_set_x(ui_TemperatureIcon, -11);
    lv_obj_set_y(ui_TemperatureIcon, 30);
    lv_obj_add_flag(ui_TemperatureIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TemperatureIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_TemperatureIcon, 125);

    ui_HumidityIcon = lv_img_create(ui_DashBoardScreen);
    lv_img_set_src(ui_HumidityIcon, &ui_img_humidity_png);
    lv_obj_set_width(ui_HumidityIcon, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_HumidityIcon, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_HumidityIcon, 4);
    lv_obj_set_y(ui_HumidityIcon, 93);
    lv_obj_add_flag(ui_HumidityIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HumidityIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HumidityIcon, 175);

    ui_WindIcon = lv_img_create(ui_DashBoardScreen);
    lv_img_set_src(ui_WindIcon, &ui_img_windspeed_png);
    lv_obj_set_width(ui_WindIcon, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_WindIcon, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_WindIcon, 13);
    lv_obj_set_y(ui_WindIcon, 145);
    lv_obj_add_flag(ui_WindIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WindIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RainIcon = lv_img_create(ui_DashBoardScreen);
    lv_img_set_src(ui_RainIcon, &ui_img_rain_png);
    lv_obj_set_width(ui_RainIcon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_RainIcon, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_RainIcon, 16);
    lv_obj_set_y(ui_RainIcon, 192);
    lv_obj_add_flag(ui_RainIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RainIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_RainIcon, 200);

    ui_Temperature = lv_label_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_Temperature, 56);
    lv_obj_set_height(ui_Temperature, 22);
    lv_obj_set_x(ui_Temperature, 67);
    lv_obj_set_y(ui_Temperature, 58);
    lv_label_set_text(ui_Temperature, "00.0");
    lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_Humidity, 56);
    lv_obj_set_height(ui_Humidity, 22);
    lv_obj_set_x(ui_Humidity, 67);
    lv_obj_set_y(ui_Humidity, 107);
    lv_label_set_text(ui_Humidity, "00.0");
    lv_obj_set_style_text_color(ui_Humidity, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Humidity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindSpeed = lv_label_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_WindSpeed, 56);
    lv_obj_set_height(ui_WindSpeed, 22);
    lv_obj_set_x(ui_WindSpeed, 67);
    lv_obj_set_y(ui_WindSpeed, 157);
    lv_label_set_text(ui_WindSpeed, "00.0");
    lv_obj_set_style_text_color(ui_WindSpeed, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WindSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WindSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WindSpeed, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Rain = lv_label_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_Rain, 56);
    lv_obj_set_height(ui_Rain, 22);
    lv_obj_set_x(ui_Rain, 67);
    lv_obj_set_y(ui_Rain, 198);
    lv_label_set_text(ui_Rain, "N");
    lv_obj_set_style_text_color(ui_Rain, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Rain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Rain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Rain, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureUnit = lv_label_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_TemperatureUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureUnit, 42);
    lv_obj_set_y(ui_TemperatureUnit, 49);
    lv_label_set_text(ui_TemperatureUnit, "oC");
    lv_obj_set_style_text_color(ui_TemperatureUnit, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureUnit, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityUnit = lv_label_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_HumidityUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityUnit, 46);
    lv_obj_set_y(ui_HumidityUnit, 106);
    lv_label_set_text(ui_HumidityUnit, "%");
    lv_obj_set_style_text_color(ui_HumidityUnit, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityUnit, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindSpeedUnit = lv_label_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_WindSpeedUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindSpeedUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindSpeedUnit, 37);
    lv_obj_set_y(ui_WindSpeedUnit, 152);
    lv_label_set_text(ui_WindSpeedUnit, "km/h");
    lv_obj_set_style_text_color(ui_WindSpeedUnit, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WindSpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WindSpeedUnit, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RainUnit = lv_label_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_RainUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RainUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RainUnit, 44);
    lv_obj_set_y(ui_RainUnit, 191);
    lv_label_set_text(ui_RainUnit, "Y/N");
    lv_obj_set_style_text_color(ui_RainUnit, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RainUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RainUnit, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomBar = lv_obj_create(ui_DashBoardScreen);
    lv_obj_set_width(ui_BottomBar, 175);
    lv_obj_set_height(ui_BottomBar, 28);
    lv_obj_set_x(ui_BottomBar, 133);
    lv_obj_set_y(ui_BottomBar, 206);
    lv_obj_clear_flag(ui_BottomBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomBar, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomBar, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Location = lv_label_create(ui_BottomBar);
    lv_obj_set_width(ui_Location, 134);
    lv_obj_set_height(ui_Location, 16);
    lv_obj_set_x(ui_Location, 31);
    lv_obj_set_y(ui_Location, 4);
    lv_label_set_text(ui_Location, "N/A");
    lv_obj_set_style_text_color(ui_Location, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Location, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Location, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SmartHomeIcon = lv_img_create(ui_BottomBar);
    lv_img_set_src(ui_SmartHomeIcon, &ui_img_smarthome_png);
    lv_obj_set_width(ui_SmartHomeIcon, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_SmartHomeIcon, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_SmartHomeIcon, -7);
    lv_obj_set_y(ui_SmartHomeIcon, -14);
    lv_obj_add_flag(ui_SmartHomeIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmartHomeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SmartHomeIcon, 150);

    lv_obj_add_event_cb(ui_DashBoardScreen, ui_event_DashBoardScreen, LV_EVENT_ALL, NULL);

}
